### PR TITLE
GitHub actions CI instead of buildkite

### PR DESCRIPTION
**Pull request by tmonfre**

### CODE REVIEW

**Comment by tmonfre** [comment]
sorry @jeffzyliu let me figure out why it's failing then I'll re-request you

**Review by jeffzyliu — COMMENTED** [review]
I think there's a conflict between the borales CI and our "engines" config in package.json. Could u just delete that section rq and then I think this will work

**Comment by tmonfre** [comment]
I'm gonna try to get away from borales as a whole

**Review by jeffzyliu — APPROVED** [review]
Is this method compatible w node 14? (Not that it matters all that much probably)

**Comment by tmonfre** [comment]
yes, I can have it run on both node 12 and 14 if we'd like, what are your thoughts?

**Comment by jeffzyliu** [comment]
I prefer to work on 14 as much as possible, is there a reason to check it against 12 at the moment?

**Comment by tmonfre** [comment]
I can switch to 14. for some reason I thought heroku was running 12 for automation, but I just checked and it's not

**Pull request merged**
